-- Oracle Database Schema for Invoice System

-- Users table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'user' NOT NULL, -- 'user' or 'admin'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invoices table
CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    supplier_name VARCHAR2(100) NOT NULL,
    invoice_number VARCHAR2(50) NOT NULL,
    amount NUMBER(15, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'open' NOT NULL, -- 'open' or 'closed'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoices_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Files table
CREATE TABLE files (
    file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    filename VARCHAR2(255) NOT NULL,
    filepath VARCHAR2(500) NOT NULL,
    used_in_invoice NUMBER DEFAULT NULL, -- invoice_id if used, else NULL
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_files_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_files_invoice FOREIGN KEY (used_in_invoice) REFERENCES invoices(invoice_id)
);

-- Invoice_Files linking table (optional, if multiple files per invoice)
-- Not strictly needed if files.used_in_invoice is used, but can be added for flexibility
-- CREATE TABLE invoice_files (
--     invoice_id NUMBER NOT NULL,
--     file_id NUMBER NOT NULL,
--     CONSTRAINT pk_invoice_files PRIMARY KEY (invoice_id, file_id),
--     CONSTRAINT fk_invoice_files_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
--     CONSTRAINT fk_invoice_files_file FOREIGN KEY (file_id) REFERENCES files(file_id)
-- );
